### ISSUE TITLE
Wrong model in the PreDuplicateModelEvent

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/dc-general#197]
I think we use a wrong model for the PreDuplicateModelEvent. We use the original model instead of the new copy model. So we can't edit it before the system writes the data to the database.

See:
https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php#L101

**Comment by discordier** [comment]
I guess so too. @dmolineus, any reason why it was implemented like this?

**Comment by dmolineus** [comment]
I just extracted it from the views, it was implemented this way before. See https://github.com/contao-community-alliance/dc-general/commit/c0e2b48e5187c1e8b0efcb0ccd7d0e762281149c#diff-23a03e40c98eb6cfd1d73e71399e6d27.

Guess it's because of the naming. It's a *pre* duplicate event. But could be useful to have the original and the copy passed to the event same as it's done with the post duplicate event.

**Comment by stefanheimes** [comment]
For what? The original is neve used again and if someone else change data on the copy why should i check the original again. I have no usecase at the moment. Have you one ?

**Comment by dmolineus** [comment]
The clone does not have an Id yet. So it won't be possilbe to handle any related data. https://github.com/contao-community-alliance/dc-general/blob/develop/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php#L496-L516

**Comment by stefanheimes** [comment]
+1

**Comment by discordier** [comment]
?
