### ISSUE TITLE
Is this a naming conflict for build a IN filter

### ISSUE THREAD

**Issue by baumannsven** [contao-community-alliance/dc-general#432]
When i build a `IN` filter so i must set to keys with the same value. The keys are `value` and `values`. I'm not sure that's what it's supposed to be here.

```php
[
    [
         'operation' => 'IN',
         'value'     => $idList,
         'values'    => $idList,
         'property'  => 'id'
    ]
]
```

https://github.com/contao-community-alliance/dc-general/blob/2.0.0-beta49/src/ContaoCommunityAlliance/DcGeneral/Data/DefaultDataProviderSqlUtils.php#L240
https://github.com/contao-community-alliance/dc-general/blob/2.0.0-beta49/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/ModelRelationship/AbstractCondition.php#L118

**Comment by baumannsven** [comment]
@discordier Your statement please

**Comment by discordier** [comment]
Should be `values` but was broken since the [initial commit](https://github.com/contao-community-alliance/dc-general/commit/fd51126cc266857421e91b3d859319388e62e372#diff-f4c06c275bfc427cf918de0588cbf0fbR69).

The [original docs](https://github.com/contao-community-alliance/dc-general/commit/322870c3d225d01f4fd33288b579b34dd1abc7af#diff-9f7504b8a872944dfaf084bf3f8f8335L374) stated it correctly

**Comment by baumannsven** [comment]
Fixed in https://github.com/contao-community-alliance/dc-general/commit/81ce3510e92e7467ccc97edee20604e73cb111a7
